### ISSUE TITLE
incompatible php version

### ISSUE THREAD

**Issue by gildas15** [sgomez/botman-bundle#2]
Please when installing botman I get the following error, something to do with the php version
![botman](https://user-images.githubusercontent.com/36203062/56350042-62721b00-61b9-11e9-92c3-46db75ef57a8.png)

**Comment by sgomez** [comment]
You need PHP 7.2 at least.

**Comment by gildas15** [comment]
this mean it cannot work with symfony 3.4

**Comment by gildas15** [comment]
Because I am using symfony 3.4

**Comment by sgomez** [comment]
Yes, it does.  https://symfony.com/blog/get-ready-for-php-7-2

**Comment by gildas15** [comment]
ok thanks for that
